SFX_MACRO(buzz        , 0)
SFX_MACRO(bounce      , 1)
SFX_MACRO(tut         , 2)
SFX_MACRO(ring        , 3)
SFX_MACRO(note        , 4)
SFX_MACRO(lfoA        , 5)
SFX_MACRO(seqplay     , 6)
SFX_MACRO(seqms       , 7)
SFX_MACRO(osc1        , 8)
SFX_MACRO(osc1wf      , 9)
SFX_MACRO(rev1        , 10)
SFX_MACRO(seqnew      , 11)
SFX_MACRO(seqvol      , 12)

#undef SFX_MACRO // need to redefine SFX_MACRO each time
